# Generated by Django 4.0.5 on 2022-07-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usermessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='title',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='textfield',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
    ]
