# Generated by Django 4.0.5 on 2022-07-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_usermessage_textfield_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='theme',
            field=models.CharField(default=1, max_length=80, verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
