# Generated by Django 4.0.5 on 2022-07-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_aboutmessage_remove_usermessage_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения (Контакты)'},
        ),
    ]
