# Generated by Django 4.0.5 on 2022-07-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_usermessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости (Статьи)'},
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': 'Пункт', 'verbose_name_plural': 'Пункты (Услуги)'},
        ),
        migrations.RenameField(
            model_name='aboutmessage',
            old_name='textfield',
            new_name='plain_message',
        ),
        migrations.RenameField(
            model_name='aboutmessage',
            old_name='theme',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='aboutmessage',
            old_name='email',
            new_name='to_email',
        ),
    ]
